

# Import

```{python}
import pandas as pd
pd.options.mode.copy_on_write= True
```

# Dataset

```{python}

counties=pd.read_csv("data/us_counties_data.csv")
```


```{python}
area_df = counties[["county","area_sq_miles","pop_20"]]
```

# Creating new variables
```{python}
# New variable area in sq km
area_df["area_sq_km"] = area_df["area_sq_miles"] * 2.59
area_df
# area_hectares
area_df["area_hectares"] = area_df["area_sq_km"] * 100
area_df
```

# Practice 
Using the area_df create new column called area_acres by multiplying are_sq_miles by 640. Store the result in area_df and display DF


```{python}
# area_hectares
area_df["area_acres"] = area_df["area_sq_miles"] * 640
area_df
```

# Modifying existing variables

```{python}
area_df["area_sq_km"]=area_df["area_sq_km"].round(1)
area_df
# if you want to change to round(2) need to re-run the code above
```

# Practice Q
Useing the "area_df" dataset round area_acres variable to one decimal place. Update DF and display *


```{python}
area_df["area_acres"] = area_df["area_acres"].round(1)
area_df
```

# Calculating with multiple variables

```{python}
# Wrapping a function 
area_df["pop_per_sq_km"]=(area_df["pop_20"]/area_df["area_sq_km"]).round(1)
# sorting a DF
area_df.sort_values(by="pop_per_sq_km", ascending=False)
area_df
```

# Practice Q
Use the counties dataset to calculate the percentage of foreign born residents in each county (x by 100 the proportion). the variable foreign_born_num shows the number of foreign-born residents and pop_20 shows the total of the population.

```{python}
# reduce df for higher lisibility
counties_fb=counties[["foreign_born_num","pop_20","county"]]
counties_fb["foreign_born_pc"]=((counties_fb["foreign_born_num"]/counties_fb["pop_20"])*100).round(1)
counties_fb.sort_values(by="foreign_born_pc", descending=True)
counties_fb
```

# Creating boolean variables 

```{python}
changes_df=counties[["county","pop_change_2010_2020","pct_emp_change_2010_2021"]]
changes_df
```


```{python}
changes_df["pop_increase"]=changes_df["pop_change_2010_2020"] > 0
changes_df["emp_increase"]=changes_df["pct_emp_change_2010_2021"]>0
changes_df
```


```{python}
changes_df.query("pop_increase==True & emp_increase==False")

changes_df.query("pop_increase & ~(emp_increase)")
```

# Practice Q
Categorise counts by foreing born population
In a previous practice question, we calculated teh % of foreing born resident/country. Create a boulean variable foreign_born_pc_gt_30 that is true if the % is greater than 30%.
when you're done query the DF to show counties where foreign_born_pc_gt_30 is true. 24 rows


```{python}
counties_fb["foreign_born_pc_gt_30"]=counties_fb["foreign_born_pc"]>30
foreign_born_pc_gt_30=counties_fb.query("foreign_born_pc_gt_30")
foreign_born_pc_gt_30
```

# Copy on Write warning

```{python}
# understanding  pd.options.mode.copy_on_write= True
pd.options.mode.copy_on_write= True
counties_mini=counties[["county","area_sq_miles"]]
counties_mini["area_sq_miles"]=counties_mini["area_sq_miles"].round(2)
counties_mini

```